openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
- url: https://d5d91accnt6pb0c1makn.zj2i1qoy.apigw.yandexcloud.net
x-yc-apigateway:
  cors:
    origin: '*'
    methods: '*'
    allowHeaders: '*'
  rateLimit:
    allRequests:
      rps: 10
paths:
  /events:
    get:
      x-yc-apigateway-rate-limit:
        allRequests:
          rps: 1
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emq722rs5knmteamr7
        tag: $latest
        service_account_id: ajeulag2umc6ufvc2tk3
        payload_format_version: '1.0'
      operationId: function-for-events-get
      security:
      - bearerAuth: []
    post:
      x-yc-apigateway-rate-limit:
        allRequests:
          rps: 1
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emq722rs5knmteamr7
        tag: $latest
        service_account_id: ajeulag2umc6ufvc2tk3
        payload_format_version: '1.0'
      operationId: function-for-events-post
      security:
      - bearerAuth: []
  /events/{event}:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emq722rs5knmteamr7
        tag: $latest
        payload_format_version: '1.0'
        service_account_id: ajeulag2umc6ufvc2tk3
      operationId: get-event
      security:
      - bearerAuth: []
      parameters:
      - description: event_id
        explode: false
        in: path
        name: event
        required: true
        schema:
          type: string
        style: simple
    put:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emq722rs5knmteamr7
        tag: $latest
        payload_format_version: '1.0'
        service_account_id: ajeulag2umc6ufvc2tk3
      operationId: put-event
      security:
      - bearerAuth: []
      parameters:
      - description: event_id
        explode: false
        in: path
        name: event
        required: true
        schema:
          type: string
        style: simple
    delete:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emq722rs5knmteamr7
        tag: $latest
        payload_format_version: '1.0'
        service_account_id: ajeulag2umc6ufvc2tk3
      operationId: delete-event
      security:
      - bearerAuth: []
      parameters:
      - description: event_id
        explode: false
        in: path
        name: event
        required: true
        schema:
          type: string
        style: simple
  /events/{event}/users:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emq722rs5knmteamr7
        tag: $latest
        payload_format_version: '1.0'
        service_account_id: ajeulag2umc6ufvc2tk3
      operationId: get-event-users
      security:
      - bearerAuth: []
      parameters:
      - description: event_id
        explode: false
        in: path
        name: event
        required: true
        schema:
          type: string
        style: simple
  /events/{event}/role:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emq722rs5knmteamr7
        tag: $latest
        payload_format_version: '1.0'
        service_account_id: ajeulag2umc6ufvc2tk3
      operationId: set-event-user-role
      security:
      - bearerAuth: []
      parameters:
      - description: event_id
        explode: false
        in: path
        name: event
        required: true
        schema:
          type: string
        style: simple
  /events/{event}/unregister:
    delete:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emq722rs5knmteamr7
        tag: $latest
        payload_format_version: '1.0'
        service_account_id: ajeulag2umc6ufvc2tk3
      operationId: event-unregister
      security:
      - bearerAuth: []
      parameters:
      - description: event_id
        explode: false
        in: path
        name: event
        required: true
        schema:
          type: string
        style: simple
  /check:
    post:
      x-yc-apigateway-rate-limit:
        allRequests:
          rps: 1
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emq722rs5knmteamr7
        tag: $latest
        service_account_id: ajeulag2umc6ufvc2tk3
        payload_format_version: '1.0'
      operationId: function-for-check-registration
      security:
      - bearerAuth: []
  /bot/events/{event}:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emq722rs5knmteamr7
        tag: $latest
        payload_format_version: '1.0'
        service_account_id: ajeulag2umc6ufvc2tk3
      operationId: get-event-from-bot
      security:
      - tokenAuth: []
      parameters:
      - description: event_id
        explode: false
        in: path
        name: event
        required: true
        schema:
          type: string
        style: simple
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emq722rs5knmteamr7
        tag: $latest
        payload_format_version: '1.0'
        service_account_id: ajeulag2umc6ufvc2tk3
      operationId: post-event-from-bot
      security:
      - tokenAuth: []
      parameters:
      - description: event_id
        explode: false
        in: path
        name: event
        required: true
        schema:
          type: string
        style: simple
components:
  securitySchemes:
    bearerAuth:
      x-yc-apigateway-authorizer:
        type: function
        function_id: d4elp1kska2us4vdik59
        tag: $latest
        service_account_id: ajeulag2umc6ufvc2tk3
        authorizer_result_ttl_in_seconds: 300
      scheme: bearer
      type: http
    tokenAuth:
      x-yc-apigateway-authorizer:
        type: function
        function_id: d4esjgf4m7g88cg0lcre
        tag: $latest
        service_account_id: ajeulag2umc6ufvc2tk3
        authorizer_result_ttl_in_seconds: 300
      scheme: bearer
      type: http

